version: "3.8"
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg14
        container_name: timescaledb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
            POSTGRES_DB: SERVER_LOG
        volumes:
            - timescale_data:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    timescale_data:
