version: "3.8"

services:
    timescaledb:
        image: timescale/timescaledb:latest-pg14
        container_name: timescaledb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
            POSTGRES_DB: SERVER_LOG
        volumes:
            - timescale_data:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672" # RabbitMQ 기본 포트
            - "15672:15672" # RabbitMQ 관리 콘솔 포트
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

volumes:
    timescale_data:
    rabbitmq_data:
